version: "3.5"

services:
    demo-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: demo-app
        container_name: demo-app 
        restart: unless-stopped
        ports:
            - 3001:3001